// Central site metadata used for SEO / social cards.
export const SITE = {
  name: 'Innov-8',
  defaultTitle: 'Innov-8 — Panel Management for UK Field Services',
  defaultDescription:
    'Innov-8 — the panel management platform for UK field services. Data-driven allocation, transparent dashboards, and performance optimisation for energy and water companies.',
  // X / Twitter handle for card attribution. TODO: confirm the real handle.
  twitter: '@innov8pm',
  // Default social card (generated by src/pages/og/[...route].ts).
  defaultOgImage: '/og/home.png',
  ogImageWidth: 1200,
  ogImageHeight: 630,
} as const
